name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: self-hosted  # Specify that this job should run on a self-hosted runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add more steps as needed
